# Generated by Django 4.0.5 on 2022-06-10 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to='works/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='upload_date',
            field=models.DateField(auto_now=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.worktype', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тип работы'),
        ),
    ]
