# Generated by Django 4.0.5 on 2022-06-17 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0002_alter_work_file_alter_work_name_alter_work_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='scientific_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scientific_director', to=settings.AUTH_USER_MODEL, verbose_name='Научный руководитель'),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, upload_to='works/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец работы'),
        ),
    ]
