# Generated by Django 4.0.5 on 2022-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_work_scientific_director_alter_work_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Работа принята'),
        ),
    ]
