# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Учебный год')),
                ('url_slug', models.IntegerField(verbose_name='URL slug')),
            ],
        ),
        migrations.AddField(
            model_name='worktype',
            name='url_slug',
            field=models.IntegerField(blank=True, null=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='work',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.academicyear', verbose_name='Учебный год'),
        ),
    ]
