# Generated by Django 4.0.5 on 2022-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_academicyear_worktype_url_slug_work_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='url_slug',
            field=models.IntegerField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='url_slug',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='URL slug'),
        ),
    ]
