# Generated by Django 4.0.5 on 2022-06-22 00:11

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_academicyear_url_slug_alter_worktype_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[works.models.validate_grade], verbose_name='Оценка'),
        ),
    ]
