# Generated by Django 4.0.5 on 2022-06-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_work_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(default='Ожидается загрузка файла', max_length=255, verbose_name='Состояние'),
        ),
    ]
